services:
  db:
    image: postgres:16-alpine
    container_name: agri_postgres_db
    restart: always
    environment:
      POSTGRES_USER: agri_user
      POSTGRES_PASSWORD: agri_password
      POSTGRES_DB: agri_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: